In [1]:
print("hello world")

hello world


In [3]:
x=10; print(x);

10


In [4]:
import numpy as np

In [58]:
x = np.array([1,2,3]); print(x)

[1 2 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
y = np.array([2,3, 4])

In [10]:
print(x+y); print(x*y); print(2*x)

[3 5 7]
[ 2  6 12]
[2 4 6]


In [35]:
z=np.array(["apple", 3])
print(z)
print(type(z))
print(z.dtype)
z.dtype

['apple' '3']
<class 'numpy.ndarray'>
<U21


dtype('<U21')

In [14]:
a = np.array([[[1,2], [3,4], [5,6]], [[5,6],[7,8], [8,9]]])

In [15]:
print(a)

[[[1 2]
  [3 4]
  [5 6]]

 [[5 6]
  [7 8]
  [8 9]]]


In [16]:
a.size

12

In [17]:
a.shape

(2, 3, 2)

In [18]:
a.ndim

3

In [19]:
x.shape

(3,)

In [20]:
a.dtype

dtype('int64')

In [21]:
x.dtype

dtype('int64')

In [22]:
type([21])

list

In [23]:
type(x.shape)

tuple

In [56]:
x=100

In [54]:
y=x+10


In [57]:
print(y)

20


In [59]:
print(x)

[1 2 3]


In [60]:
x[0]

np.int64(1)

In [61]:
print(x[0])

1


In [62]:
print(x[-1])

3


In [63]:
print(x[-20])

IndexError: index -20 is out of bounds for axis 0 with size 3

In [64]:
x[1.5]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [65]:
x["dl"]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [66]:
x[1:1]

array([], dtype=int64)

In [67]:
print(x[1:1])

[]


In [68]:
print(x[0:1])

[1]


In [69]:
print(x[:2])

[1 2]


In [70]:
print(x[0:])

[1 2 3]


In [71]:
print(x[1:])

[2 3]


In [72]:
print(x[:])

[1 2 3]


In [73]:
print(x[::2])

[1 3]


In [74]:
print(x[[0,2]])

[1 3]


In [78]:
print(x[int(1.0)])

2


In [76]:
type(1.0)

float

In [77]:
int(1.0)

1

In [79]:
int("apple")

ValueError: invalid literal for int() with base 10: 'apple'

In [80]:
x=np.arange(12)

In [81]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [83]:
B=x.reshape(3,4)

In [84]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [85]:
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [96]:
A = x.reshape(2,2,3)

In [87]:
print(A)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [88]:
C = x.reshape(-1, 3)

In [89]:
print(C)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [90]:
D = x.reshape(-1,-1,3)

ValueError: can only specify one unknown dimension

In [91]:
print(z)

['apple' '3']


In [93]:
D = z.reshape(2,-1)

In [94]:
print(D)

[['apple']
 ['3']]


In [95]:
x.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [97]:
print(A)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [98]:
A+1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
print(A)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [100]:
A*2

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[12, 14, 16],
        [18, 20, 22]]])

In [101]:
A+ np.array([1,2])

ValueError: operands could not be broadcast together with shapes (2,2,3) (2,) 

In [102]:
print(z)

['apple' '3']


In [103]:
z.shape

(2,)

In [104]:
D = z.reshape(2,1);

In [105]:
print(D)

[['apple']
 ['3']]


In [106]:
D = z.reshape(1,2)

In [107]:
print(D)

[['apple' '3']]


In [108]:
x=np.array([1,2,3])

In [109]:
x.shape

(3,)

In [110]:
row = x.reshape(1,3)

In [111]:
col = x.reshape(3,1)

In [112]:
row @ col

array([[14]])

In [113]:
col @ row

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [114]:
print(row)

[[1 2 3]]


In [115]:
print(col)

[[1]
 [2]
 [3]]


In [116]:
print(y)

20


In [121]:
y = np.array([1,2]); print(y); print(x)

[1 2]
[1 2 3]


In [118]:
x*y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [119]:
x@y

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [122]:
y@x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)